/*
  mutation类型采用全大写加下划线的方式
*/
export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERID = 'GET_USERID'
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_QUICKENTRANCE = 'GET_QUICKENTRANCE'
export const GET_MENU = 'GET_MENU'
export const DELELE_USERINFO = 'DELELE_USERINFO'
export const GET_PAYTIP = 'GET_PAYTIP'
export const SET_API_HOST = 'SET_API_HOST'
export const SET_INDEX_HOST = 'SET_INDEX_HOST'
export const SET_MALLMEMBER_HOST = 'SET_MALLMEMBER_HOST'
export const SET_MEMBER_HOST = 'SET_MEMBER_HOST'
export const SET_THIRDMEMBER_HOST = 'SET_THIRDMEMBER_HOST'
